### ISSUE TITLE
Unable to establish connection over UDP

### ISSUE THREAD

**Issue by yinyee** [vmaffione/rlite#18]
Following along on this tutorial: https://github.com/vmaffione/rlite#53-hands-on-tutorial-2-normal-over-shim-udp4.

Node x is called Sprout (hence sproutgateway.IPCP and sproutnorm.IPCP) and node y is called Dime (ditto dimegateway.IPCP and dimenorm.IPCP).

After creating the two processes for each node and attempting to register the normal IPCP to the udptunnel DIF:

On Sprout:
- no logs output by `rlite-uipcps` after `ipcp-register` and `rlite-ctl regs-show` show no locally registered applications
- running `sudo rlite-ctl ipcp-register sproutnorm.IPCP udptunnel.DIF` for the second time; `rlite-uipicps` logs:
```
[1]update_lower_diffs: DIF udptunnel.DIF was already registered
```
But `rlite-ctl regs-show` still show no locally registered applications.

On Dime:
- no logs output by `rlite-uipcps` after `ipcp-register`
- running `sudo rlite-ctl ipcp-enroller-enable dimenorm.IPCP` seems to trigger `rlite-uipcps` logs for both the registration and the enrollment:
```
[1]enroller_enable: Enroller enabled
[0]rina_name_to_ipaddr: 'dimenorm.IPCP' --> '172.31.48.208'
[0]rina_name_to_ipaddr: 'normal.DIF' --> '172.31.48.208'
[0]udp4_bindpoint_open: bind() failed [98]
[1]register_to_lower_one: Registration of DAF name normal.DIF into DIF udptunnel.DIF failed
```
Running `rlite-ctl regs-show` on Dime:
```
Locally registered applications:
  ipcp 0, name dimenorm.IPCP
  ipcp 1, name homestead-server 
```
although there is no difference in the steps I've taken on Sprout and Dime, except to enable the enroller on dimenorm.IPCP.  Homestead is a separate node which is only listening (not sure if relevant).

I tried running `sudo rlite-ctl ipcp-enroll sproutnorm.IPCP normal.DIF udptunnel.DIF dimenorm.IPCP` anyway just to see and got:
```
read_response: Operation failed
ipcp_enroll_common: Enrollment failed
```
`rlite-uipcps` logs:
```
[1]enrollment_rsrc_get: setup enrollment data for neigh dimenorm.IPCP
[1] enroll_state_set: switch state NONE --> ENROLLING
[1]enrollee_thread: I --> S M_CONNECT
[1]next_enroll_msg: Timed out
[1]enrollment_abort: Aborting enrollment
[1]enroll_state_set: switch state ENROLLING --> NONE
[1]enrollment_rsrc_put: clean up enrollment data for neigh dimenorm.IPCP
```

After killing and restarting `rlite-uipcps`, the IPCP table still shows two entries for each node.

**Comment by vmaffione** [comment]
Hi,
  I just tried the tutorial again, and everything works as expected.
Are you sure you have followed the exact instructions (apart from changing the names consistently)? It doesn't seem so from your output.

Some observations:
  - It's ok to have no log on `ipcp-register`, because the registration is delayed until the IPCP is enrolled (either through `ipcp-enroller-enable` or `ipcp-enroll`), and consequently `regs-show` shows no output until then. Since it can be confusing I can add a log to say that registration will be postponed.
  - Don't worry about the error `Registration of DAF name normal.DIF into DIF udptunnel.DIF failed`. It's a failure that happens because the normal IPCP tries to register a "broadcast name" (e.g. the name of the DIF `rina_name_to_ipaddr: 'normal.DIF' --> '172.31.48.208'`) in addition to the "unicast name" (the name of the IPCP, `rina_name_to_ipaddr: 'dimenorm.IPCP' --> '172.31.48.208'`). However, I see you have added an entry for the broadcast name that clashes with the entry for the unicast name. This causes the bind() to fail. Can you try to follow the tutorial without changing anything but the names?

**Comment by vmaffione** [comment]
If you happen to retry the tutorial, please use the master branch. Do not add additional RINA-related configuration to `/etc/hosts`, but only the configuration specified in the tutorial.

**Comment by matt-williams** [comment]
I've tried again (on fresh VMs), and successfully got the connection up, using

*   the master branch (previously we'd been using the next branch, as advised by Marco from [Arcfire](http://ict-arcfire.eu/)
*   just the DNS records specified in the article.

Having said that, we did have this working last Saturday, and then, when we came back to it on Sunday, the tunnel had failed and wouldn't come back up (which is why @yinyee raised the issue she did).  I haven't left the tunnel up for any significant period of time, so I can't confirm that's fixed.

BTW, would it be possible to fix (or document) the misleading error in the second bullet above?  (I suspect it may have been that that threw off a lot of our investigation!)

**Comment by vmaffione** [comment]
Yes, at that time the next branch was the right one, but it was only temporary. Now the master branch is the one to use. Anyway, there was no difference w.r.t. shim-udp4, which was working in all cases (it has not changed).

So yes, I think that the misleading error was the one that put you guys on the wrong way (i.e. you probably added wrong entries to the /etc/hosts because of the error).
Following your suggestions, I documented the issue here https://github.com/vmaffione/rlite/blame/master/README.md#L579-L580. Also, I slightly changed the code to flag the failure to register a DAF name as a "warning", and not as an "error". This is correct because this failure is abbout an optional capability (the system can keep working well without it).

**Comment by vmaffione** [comment]
I would close this issue as there is nothing to be done here.
Should more problem arise with shim-udp, please open additional issues.
